"""Names for DK64 songs and sound effects (the ROM stores none).

* Song names and types: DK64 Randomizer ``randomizer/Lists/Songs.py`` (MIT, COMMUNITY);
  its ``mem_idx`` is the pointer-table-0 index.
* Fallback song names: the decompilation's ``MUSIC_E`` enum (CC0).
* Sound-effect names: the decompilation's ``SFX_E`` enum (CC0); it names only the
  arcade sounds, all other effects keep their number.
Generated once from those sources; names are labels, not official titles.
"""

from __future__ import annotations

# table-0 index -> (name, Randomizer song type)
SONGS: dict[int, tuple[str, str]] = {
    0: ('Silence', 'System'),
    1: ('Jungle Japes (Starting Area)', 'BGM'),
    2: ("Cranky's Lab", 'BGM'),
    3: ('Jungle Japes (Minecart)', 'BGM'),
    4: ('Jungle Japes (Army Dillo)', 'BGM'),
    5: ('Jungle Japes (Caves/Underground)', 'BGM'),
    6: ("Funky's Hut", 'BGM'),
    7: ('Unused Coin Pickup', 'Protected'),
    8: ('Bonus Minigames', 'BGM'),
    9: ('Triangle Trample', 'Event'),
    10: ('Guitar Gazump', 'Event'),
    11: ('Bongo Blast', 'Event'),
    12: ('Trombone Tremor', 'Event'),
    13: ('Saxophone Slam', 'Event'),
    14: ('Angry Aztec', 'BGM'),
    15: ('Transformation', 'Event'),
    16: ('Mini Monkey', 'BGM'),
    17: ('Hunky Chunky', 'BGM'),
    18: ('Golden Banana/Key Get', 'MajorItem'),
    19: ('Angry Aztec (Beetle Slide)', 'BGM'),
    20: ('Oh Banana', 'MajorItem'),
    21: ('Angry Aztec (Temple)', 'BGM'),
    22: ('Company Coin Get', 'MajorItem'),
    23: ('Banana Coin Get', 'MinorItem'),
    24: ('Going through Vulture Ring', 'Event'),
    25: ('Angry Aztec (Dogadon)', 'BGM'),
    26: ('Angry Aztec (5DT)', 'BGM'),
    27: ('Frantic Factory (Car Race)', 'BGM'),
    28: ('Frantic Factory', 'BGM'),
    29: ("Snide's HQ", 'BGM'),
    30: ('Jungle Japes (Tunnels)', 'BGM'),
    31: ("Candy's Music Shop", 'BGM'),
    32: ('Minecart Coin Get', 'MinorItem'),
    33: ('Melon Slice Get', 'MinorItem'),
    34: ('Pause Menu', 'BGM'),
    35: ('Crystal Coconut Get', 'MinorItem'),
    36: ('Rambi', 'BGM'),
    37: ('Angry Aztec (Tunnels)', 'BGM'),
    38: ('Water Droplets', 'Ambient'),
    39: ('Frantic Factory (Mad Jack)', 'BGM'),
    40: ('Success', 'Event'),
    41: ('Start (To pause game)', 'Protected'),
    42: ('Failure', 'Event'),
    43: ('DK Transition (Opening)', 'System'),
    44: ('DK Transition (Closing)', 'System'),
    45: ('Unused High-Pitched Japes', 'Protected'),
    46: ('Fairy Tick', 'MinorItem'),
    47: ('Melon Slice Drop', 'MinorItem'),
    48: ('Angry Aztec (Chunky Klaptraps)', 'BGM'),
    49: ('Frantic Factory (Crusher Room)', 'BGM'),
    50: ('Jungle Japes (Baboon Blast)', 'BGM'),
    51: ('Frantic Factory (R&D)', 'BGM'),
    52: ('Frantic Factory (Production Room)', 'BGM'),
    53: ("Troff 'n' Scoff", 'BGM'),
    54: ('Boss Defeat', 'Event'),
    55: ('Angry Aztec (Baboon Blast)', 'BGM'),
    56: ('Gloomy Galleon (Outside)', 'BGM'),
    57: ('Boss Unlock', 'Event'),
    58: ('Awaiting Entering the Boss', 'BGM'),
    59: ('Generic Twinkly Sounds', 'Ambient'),
    60: ('Gloomy Galleon (Pufftoss)', 'BGM'),
    61: ('Gloomy Galleon (Seal Race)', 'BGM'),
    62: ('Gloomy Galleon (Tunnels)', 'BGM'),
    63: ('Gloomy Galleon (Lighthouse)', 'BGM'),
    64: ('Battle Arena', 'BGM'),
    65: ('Drop Coins (Minecart)', 'MinorItem'),
    66: ('Fairy Nearby', 'Ambient'),
    67: ('Checkpoint', 'MinorItem'),
    68: ('Fungi Forest (Day)', 'BGM'),
    69: ('Blueprint Get', 'MajorItem'),
    70: ('Fungi Forest (Night)', 'BGM'),
    71: ('Strong Kong', 'BGM'),
    72: ('Rocketbarrel Boost', 'BGM'),
    73: ('Orangstand Sprint', 'BGM'),
    74: ('Fungi Forest (Minecart)', 'BGM'),
    75: ('DK Rap', 'Protected'),
    76: ('Blueprint Drop', 'MajorItem'),
    77: ('Gloomy Galleon (2DS)', 'BGM'),
    78: ('Gloomy Galleon (5DS/Submarine)', 'BGM'),
    79: ('Gloomy Galleon (Pearls Chest)', 'BGM'),
    80: ('Gloomy Galleon (Mermaid Palace)', 'BGM'),
    81: ('Fungi Forest (Dogadon)', 'BGM'),
    82: ('Mad Maze Maul', 'BGM'),
    83: ('Crystal Caves', 'BGM'),
    84: ('Crystal Caves (Giant Kosha Tantrum)', 'BGM'),
    85: ('Nintendo Logo (Old?)', 'System'),
    86: ('Success (Races)', 'Event'),
    87: ('Failure (Races & Try Again)', 'Event'),
    88: ('Bonus Barrel Introduction', 'Protected'),
    89: ('Stealthy Snoop', 'BGM'),
    90: ('Minecart Mayhem', 'BGM'),
    91: ('Gloomy Galleon (Mechanical Fish)', 'BGM'),
    92: ('Gloomy Galleon (Baboon Blast)', 'BGM'),
    93: ('Fungi Forest (Anthill)', 'BGM'),
    94: ('Fungi Forest (Barn)', 'BGM'),
    95: ('Fungi Forest (Mill)', 'BGM'),
    96: ('Generic Seaside Sounds', 'Ambient'),
    97: ('Fungi Forest (Spider)', 'BGM'),
    98: ('Fungi Forest (Mushroom Top Rooms)', 'BGM'),
    99: ('Fungi Forest (Giant Mushroom)', 'BGM'),
    100: ('Boss Introduction', 'BGM'),
    101: ('Tag Barrel (All of them)', 'Protected'),
    102: ('Crystal Caves (Beetle Race)', 'BGM'),
    103: ('Crystal Caves (Igloos)', 'BGM'),
    104: ('Mini Boss', 'BGM'),
    105: ('Creepy Castle', 'BGM'),
    106: ('Creepy Castle (Minecart)', 'BGM'),
    107: ('Baboon Balloon', 'Event'),
    108: ('Gorilla Gone', 'BGM'),
    109: ('DK Isles', 'BGM'),
    110: ("DK Isles (K. Rool's Ship)", 'BGM'),
    111: ('DK Isles (Banana Fairy Island)', 'BGM'),
    112: ("DK Isles (K. Lumsy's Prison)", 'BGM'),
    113: ('Hideout Helm (Blast-O-Matic On)', 'BGM'),
    114: ('Move Get', 'MajorItem'),
    115: ('Gun Get', 'MajorItem'),
    116: ('Hideout Helm (Blast-O-Matic Off)', 'BGM'),
    117: ('Hideout Helm (Bonus Barrels)', 'BGM'),
    118: ('Crystal Caves (Cabins)', 'BGM'),
    119: ('Crystal Caves (Rotating Room)', 'BGM'),
    120: ('Crystal Caves (Tile Flipping)', 'BGM'),
    121: ('Creepy Castle (Tunnels)', 'BGM'),
    122: ('Intro Story Medley', 'BGM'),
    123: ('Training Grounds', 'BGM'),
    124: ('Enguarde', 'BGM'),
    125: ('K. Lumsy Celebration', 'BGM'),
    126: ('Creepy Castle (Crypt)', 'BGM'),
    127: ('Headphones Get', 'MajorItem'),
    128: ('Pearl Get', 'MajorItem'),
    129: ('Creepy Castle (Dungeon w/ Chains)', 'BGM'),
    130: ('Angry Aztec (Lobby)', 'BGM'),
    131: ('Jungle Japes (Lobby)', 'BGM'),
    132: ('Frantic Factory (Lobby)', 'BGM'),
    133: ('Gloomy Galleon (Lobby)', 'BGM'),
    134: ('Main Menu', 'BGM'),
    135: ('Creepy Castle (Inner Crypts)', 'BGM'),
    136: ('Creepy Castle (Ballroom)', 'BGM'),
    137: ('Creepy Castle (Greenhouse)', 'BGM'),
    138: ("K. Rool's Theme", 'BGM'),
    139: ('Creepy Castle (Shed)', 'BGM'),
    140: ('Creepy Castle (Wind Tower)', 'BGM'),
    141: ('Creepy Castle (Tree)', 'BGM'),
    142: ('Creepy Castle (Museum)', 'BGM'),
    143: ('Barrel Blast Final Star', 'Event'),
    144: ('Drop Rainbow Coin', 'MajorItem'),
    145: ('Rainbow Coin Get', 'MajorItem'),
    146: ('Normal Star', 'MinorItem'),
    147: ('Bean Get', 'MajorItem'),
    148: ('Crystal Caves (Army Dillo)', 'BGM'),
    149: ('Creepy Castle (King Kut-Out)', 'BGM'),
    150: ('Creepy Castle (Dungeon w/out Chains)', 'BGM'),
    151: ('Banana Medal Get', 'MajorItem'),
    152: ("K. Rool's Battle", 'BGM'),
    153: ('Fungi Forest (Lobby)', 'BGM'),
    154: ('Crystal Caves (Lobby)', 'BGM'),
    155: ('Creepy Castle (Lobby)', 'BGM'),
    156: ('Hideout Helm (Lobby)', 'BGM'),
    157: ('Creepy Castle (Trash Can)', 'BGM'),
    158: ('End Sequence', 'BGM'),
    159: ('K. Lumsy Ending', 'BGM'),
    160: ('Jungle Japes', 'BGM'),
    161: ("Jungle Japes (Cranky's Area)", 'BGM'),
    162: ('K. Rool Takeoff', 'BGM'),
    163: ('Crystal Caves (Baboon Blast)', 'BGM'),
    164: ('Fungi Forest (Baboon Blast)', 'BGM'),
    165: ('Creepy Castle (Baboon Blast)', 'BGM'),
    166: ("DK Isles (Snide's Room)", 'BGM'),
    167: ("K. Rool's Entrance", 'BGM'),
    168: ('Monkey Smash', 'BGM'),
    169: ('Fungi Forest (Rabbit Race)', 'BGM'),
    170: ('Game Over', 'Protected'),
    171: ('Wrinkly Kong', 'BGM'),
    172: ('100th CB Get', 'Event'),
    173: ("K. Rool's Defeat", 'Protected'),
    174: ('Nintendo Logo', 'BGM'),
    175: ('Fake Fairy Nearby', 'Ambient'),
}

# table-0 index -> decompilation MUSIC_E name
MUSIC_ENUM: dict[int, str] = {
    0: 'Silence',
    1: 'Jungle Japes Starting Area',
    2: 'Crankys Lab',
    3: 'Jungle Japes Minecart',
    4: 'Jungle Japes Army Dillo',
    5: 'Jungle Japes Caves Underground',
    6: 'Funkys Hut',
    7: 'Unused Coin Pickup',
    8: 'Bonus Minigames',
    9: 'Triangle Trample',
    10: 'Guitar Gazump',
    11: 'Bongo Blast',
    12: 'Trombone Tremor',
    13: 'Saxophone Slam',
    14: 'Angry Aztec',
    15: 'Transformation',
    16: 'Mini Monkey',
    17: 'Hunky Chunky',
    18: 'Gb Key Get',
    19: 'Angry Aztec Beetle Slide',
    20: 'Oh Banana',
    21: 'Angry Aztec Temple',
    22: 'Company Coin Get',
    23: 'Banana Coin Get',
    24: 'Going Through Vulture Ring',
    25: 'Angry Aztec Dogadon',
    26: 'Angry Aztec 5dt',
    27: 'Frantic Factory Car Race',
    28: 'Frantic Factory',
    29: 'Snides Hq',
    30: 'Jungle Japes Tunnels',
    31: 'Candys Music Shop',
    32: 'Minecart Coin Get',
    33: 'Melon Slice Get',
    34: 'Pause Menu',
    35: 'Crystal Coconut Get',
    36: 'Rambi',
    37: 'Angry Aztec Tunnels',
    38: 'Water Droplets',
    39: 'Frantic Factory Mad Jack',
    40: 'Success',
    41: 'Start To Pause Game',
    42: 'Failure',
    43: 'Dk Transition Opening',
    44: 'Dk Transition Closing',
    45: 'Unused High Pitched Japes',
    46: 'Fairy Tick',
    47: 'Melon Slice Drop',
    48: 'Angry Aztec Chunky Klaptraps',
    49: 'Frantic Factory Crusher Room',
    50: 'Jungle Japes Baboon Blast',
    51: 'Frantic Factory Rnd',
    52: 'Frantic Factory Production Room',
    53: 'Troff N Scoff',
    54: 'Boss Defeat',
    55: 'Angry Aztec Baboon Blast',
    56: 'Gloomy Galleon Outside',
    57: 'Boss Unlock',
    58: 'Awaiting Entering The Boss',
    59: 'Generic Twinkly Sounds',
    60: 'Gloomy Galleon Pufftoss',
    61: 'Gloomy Galleon Seal Race',
    62: 'Gloomy Galleon Tunnels',
    63: 'Gloomy Galleon Lighthouse',
    64: 'Battle Arena',
    65: 'Drop Coins Minecart',
    66: 'Fairy Nearby',
    67: 'Checkpoint',
    68: 'Fungi Forest Day',
    69: 'Blueprint Get',
    70: 'Fungi Forest Night',
    71: 'Strong Kong',
    72: 'Rocketbarrel Boost',
    73: 'Orangstand Sprint',
    74: 'Fungi Forest Minecart',
    75: 'Dk Rap',
    76: 'Blueprint Drop',
    77: 'Gloomy Galleon 2ds',
    78: 'Gloomy Galleon 5ds Submarine',
    79: 'Gloomy Galleon Pearls Chest',
    80: 'Gloomy Galleon Mermaid Palace',
    81: 'Fungi Forest Dogadon',
    82: 'Mad Maze Maul',
    83: 'Crystal Caves',
    84: 'Crystal Caves Giant Kosha Tantrum',
    85: 'Nintendo Logo Old',
    86: 'Success Races',
    87: 'Failure Races Try Again',
    88: 'Bonus Barrel Introduction',
    89: 'Stealthy Snoop',
    90: 'Minecart Mayhem',
    91: 'Gloomy Galleon Mechanical Fish',
    92: 'Gloomy Galleon Baboon Blast',
    93: 'Fungi Forest Anthill',
    94: 'Fungi Forest Barn',
    95: 'Fungi Forest Mill',
    96: 'Generic Seaside Sounds',
    97: 'Fungi Forest Spider',
    98: 'Fungi Forest Mushroom Top Rooms',
    99: 'Fungi Forest Giant Mushroom',
    100: 'Boss Introduction',
    101: 'Tag Barrel All Of Them',
    102: 'Crystal Caves Beetle Race',
    103: 'Crystal Caves Igloos',
    104: 'Mini Boss',
    105: 'Creepy Castle',
    106: 'Creepy Castle Minecart',
    107: 'Baboon Balloon',
    108: 'Gorilla Gone',
    109: 'Dk Isles',
    110: 'Dk Isles K Rools Ship',
    111: 'Dk Isles Banana Fairy Island',
    112: 'Dk Isles K Lumsys Prison',
    113: 'Hideout Helm Blast O Matic On',
    114: 'Move Get',
    115: 'Gun Get',
    116: 'Hideout Helm Blast O Matic Off',
    117: 'Hideout Helm Bonus Barrels',
    118: 'Crystal Caves Cabins',
    119: 'Crystal Caves Rotating Room',
    120: 'Crystal Caves Tile Flipping',
    121: 'Creepy Castle Tunnels',
    122: 'Intro Story Medley',
    123: 'Training Grounds',
    124: 'Enguarde',
    125: 'K Lumsy Celebration',
    126: 'Creepy Castle Crypt',
    127: 'Headphones Get',
    128: 'Pearl Get',
    129: 'Creepy Castle Dungeon W Chains',
    130: 'Angry Aztec Lobby',
    131: 'Jungle Japes Lobby',
    132: 'Frantic Factory Lobby',
    133: 'Gloomy Galleon Lobby',
    134: 'Main Menu',
    135: 'Creepy Castle Inner Crypts',
    136: 'Creepy Castle Ballroom',
    137: 'Creepy Castle Greenhouse',
    138: 'K Rools Theme',
    139: 'Creepy Castle Shed',
    140: 'Creepy Castle Wind Tower',
    141: 'Creepy Castle Tree',
    142: 'Creepy Castle Museum',
    143: 'Bblast Final Star',
    144: 'Drop Rainbow Coin',
    145: 'Rainbow Coin Get',
    146: 'Normal Star',
    147: 'Bean Get',
    148: 'Crystal Caves Army Dillo',
    149: 'Creepy Castle Kut Out',
    150: 'Creepy Castle Dungeon W Out Chains',
    151: 'Banana Medal Get',
    152: 'K Rools Battle',
    153: 'Fungi Forest Lobby',
    154: 'Crystal Caves Lobby',
    155: 'Creepy Castle Lobby',
    156: 'Hideout Helm Lobby',
    157: 'Creepy Castle Trash Can',
    158: 'End Sequence',
    159: 'K Lumsy Ending',
    160: 'Jungle Japes',
    161: 'Jungle Japes Crankys Area',
    162: 'K Rool Takeoff',
    163: 'Crystal Caves Baboon Blast',
    164: 'Fungi Forest Baboon Blast',
    165: 'Creepy Castle Baboon Blast',
    166: 'Dk Isles Snides Room',
    167: 'K Rools Entrance',
    168: 'Monkey Smash',
    169: 'Fungi Forest Rabbit Race',
    170: 'Game Over',
    171: 'Wrinkly Kong',
    172: '100th Cb Get',
    173: 'K Rools Defeat',
    174: 'Nintendo Logo',
}

# sound number -> decompilation SFX_E name
SFX_ENUM: dict[int, str] = {
    0: 'Silence',
    64: 'Arcade Jumpman Moving',
    65: 'Arcade Jumpman Jumping',
    66: 'Arcade Jumpman Hit',
    67: 'Arcade Spring Springing',
    68: 'Arcade Spring Fall',
    69: 'Arcade Points',
    70: 'Arcade Intro',
    72: 'Arcade Running Out Of Time',
    73: 'Arcade Hammer Music',
    75: 'Arcade Hammer Attack',
    76: 'Arcade Pauline Saved Stage',
    77: 'Arcade 25m',
    78: 'Arcade 100m',
    79: 'Arcade 50m',
    83: 'Arcade Dk Grunt',
    84: 'Arcade Jumpman Death',
}


def song_name(index: int) -> str:
    if index in SONGS:
        return SONGS[index][0]
    return MUSIC_ENUM.get(index, "")


def song_note(index: int) -> str:
    if index in SONGS:
        return "DK64 Randomizer song list (COMMUNITY)"
    if index in MUSIC_ENUM:
        return "decompilation MUSIC_E enum (COMMUNITY)"
    return "none"


def song_type(index: int) -> str:
    return SONGS[index][1] if index in SONGS else ""


def sfx_label(index: int) -> str:
    return SFX_ENUM.get(index, "") if index else ""


def sfx_note(index: int) -> str:
    return "decompilation SFX_E enum (COMMUNITY)" if sfx_label(index) else "no name in any source"
