"""Display names for DK64 actor models and maps (no names are stored in the ROM for these).

ACTOR_MODEL_NAMES: index = Actor Geometry table-5 entry = in-game model id. Source: DK64 Randomizer
`randomizer/Enums/Models.py` `class Model` (MIT License, Copyright (c) 2023 DK64 Randomizer Dev Team;
see licenses/THIRD_PARTY.md). COMMUNITY names.
MAP_NAMES: index = map id = Map Geometry table-1 entry. Source: dk64_decomp `include/enums.h` map enum
(CC0 1.0). Decomp identifiers, title-cased.
Prop (model-two) names come from the ROM itself (texture_bank.prop_name).
"""

ACTOR_MODEL_NAMES = (
    "Diddy",
    "Diddy With Instrument",
    "Diddy Low Poly",
    "DK",
    "DKLow Poly",
    "Lanky",
    "Lanky With Instrument",
    "Lanky Low Poly",
    "Tiny",
    "Tiny With Instrument",
    "Tiny Low Poly",
    "Chunky",
    "Chunky With Instrument",
    "Chunky Disco",
    "Chunky Low Poly",
    "Chunky Gone",
    "Cranky",
    "Funky",
    "Candy",
    "Rambi",
    "Snake",
    "Turtle",
    "Seal",
    "Enguarde",
    "Beaver Blue_Low Poly",
    "Beaver Blue",
    "Beaver Gold",
    "Zinger",
    "Squawks_28",
    "Klobber",
    "Snide",
    "Kaboom",
    "Klaptrap Green",
    "Klaptrap Purple",
    "Klaptrap Red",
    "Klaptrap Teeth",
    "Mad Jack",
    "Krash",
    "Troff",
    "Toy Monster",
    "Sir Domino",
    "Mr Dice_41",
    "Ruler",
    "Robo Kremling",
    "Scoff",
    "Beetle",
    "Klaptrap Unk",
    "Nintendo Logo",
    "Kremling",
    "Kosh Kremling Red",
    "Kosh Kremling",
    "Mechanical Fish",
    "Toy Car",
    "Giant Clam",
    "Kasplat",
    "Army Dillo",
    "Mr Dice_56",
    "Klump",
    "Puftoss",
    "Dogadon",
    "Banana Fairy",
    "Llama",
    "Guard",
    "Robo Zinger",
    "Turntable",
    "Krossbones",
    "Shuri",
    "Gimpfish",
    "KLumsy",
    "Spider",
    "Rabbit",
    "Beanstalk",
    "KRool Cutscene",
    "Fireball With Glasses",
    "Skeleton Head",
    "Skeleton Hand",
    "Vulture_76",
    "Vulture_77",
    "Bat",
    "Skull",
    "Tomato",
    "Ghost",
    "Fly",
    "Fly Swatter_83",
    "Fly Swatter_84",
    "Owl",
    "Book",
    "Ship Wheel",
    "Spotlight Fish",
    "Puftup",
    "Mermaid",
    "Mushroom",
    "Shockwave MJ",
    "Squawks_93",
    "Worm",
    "Cuckoo Bird",
    "Kosha",
    "Ice Tomato",
    "Army Dillo No Shell",
    "Boombox",
    "BLocker",
    "Escape Ship",
    "Army Dillo Cannon",
    "KRool Fight",
    "Golden Banana_104",
    "Shockwave",
    "KRool Glove",
    "KRool Foot",
    "KRool Toe_108",
    "KRool Toe_109",
    "KRool Toe_110",
    "Microphone",
    "Desk KRool",
    "Bell",
    "Clapper Board",
    "Cannon_115",
    "Barrel_116",
    "Bonus Barrel",
    "Hunky Chunky Barrel",
    "Mini Monkey Barrel",
    "Barrel_120",
    "Pushable Box",
    "TNTBarrel Spawner",
    "Cannon_123",
    "TNTBarrel",
    "Rambi Crate",
    "Enguarde Crate",
    "Chain",
    "Swinging Light_128",
    "Minecart",
    "Barrel",
    "Bridge Castle",
    "Large Brown Bridge",
    "Feather",
    "Laser",
    "Golden Banana",
    "Rocketbarrel",
    "Strong Kong Barrel",
    "Orangstand Sprint Barrel",
    "Diddy Jetpack",
    "Photo",
    "Minecart TNT",
    "Window Screen",
    "BBBSlot_143",
    "BBBSlot_144",
    "BBBSlot_145",
    "BBBSlot_146",
    "BBBLever",
    "Player Car",
    "Missile",
    "Swinging Light_150",
    "Bananaporter Zipper",
    "Boulder",
    "Vase Circle",
    "Vase Colon",
    "Vase Triangle",
    "Vase Plus",
    "Toy Box",
    "Boat_158",
    "Padlock",
    "Cannon Ball",
    "Vine_161",
    "Vine_162",
    "Counter",
    "Key",
    "Bongos",
    "DKStar",
    "Spotlight",
    "Cannon Seasick",
    "Boulder Debris",
    "Spider Web",
    "Steel Keg",
    "Shockwave_172",
    "Shockwave_173",
    "Battle Crown",
    "Buoy",
    "Buoy Green",
    "Unknown",
    "DKBanana Counter",
    "Diddy Banana Counter",
    "Tiny Banana Counter",
    "Lanky Banana Counter",
    "Chunky Banana Counter",
    "Shockwave Green_183",
    "Potion",
    "Army Dillo Missle",
    "Shockwave Red",
    "Ice Wall",
    "Rareware Logo",
    "Stalactite",
    "Rock Debris",
    "Spotlight Bonus",
    "Tag Barrel",
    "Krossbones Head",
    "Lever",
    "KLumsy Cage",
    "Ice Trap Bubble",
    "Diddy Barrel Pad_1",
    "Diddy Barrel Pad_2",
    "Diddy Barrel Pad_3",
    "Diddy Barrel Pad_4",
    "Diddy Barrel Pad_5",
    "Diddy Barrel Pad_6",
    "Race Checkpoint",
    "Padlock And Key",
    "Finish Line",
    "Shockwave Green_206",
    "Shockwave Blue",
    "Shockwave Purple",
    "Question Mark",
    "Flower With Instrument",
    "DKLogo With Instrument",
    "Golden Banana_212",
    "Apple",
    "Barrel_214",
    "Flag_215",
    "Flag_216",
    "Boat_217",
    "Krusha",
    "King Kut Out Body",
    "King Kut Out Head",
    "King Kut Out Arm_221",
    "King Kut Out Arm_222",
    "Dirt Patch",
    "Rope",
    "DKSmoke Trail",
    "Light",
    "Helm Barrel",
    "Banana Peel",
    "Banana Barrel",
    "Training Barrel",
    "Pirate Photo",
    "Butterfly",
    "Barrel_233",
    "Funky Gun",
    "Boot",
)

MAP_NAMES = {
    0: "Test Map",
    1: "Funkys Store",
    2: "Dk Arcade",
    3: "Krool Barrel Lanky Maze",
    4: "Japes Mountain",
    5: "Crankys Lab",
    6: "Japes Minecart",
    7: "Japes",
    8: "Japes Army Dillo",
    9: "Jetpac",
    10: "Kremling Kosh Very Easy",
    11: "Stealthy Snoop Normal No Logo",
    12: "Japes Shell",
    13: "Japes Lanky Cave",
    14: "Aztec Beetle Race",
    15: "Snides Hq",
    16: "Aztec Tiny Temple",
    17: "Helm",
    18: "Teetering Turtle Trouble Very Easy",
    19: "Aztec Five Door Temple Dk",
    20: "Aztec Llama Temple",
    21: "Aztec Five Door Temple Diddy",
    22: "Aztec Five Door Temple Tiny",
    23: "Aztec Five Door Temple Lanky",
    24: "Aztec Five Door Temple Chunky",
    25: "Candys Music Shop",
    26: "Factory",
    27: "Factory Car Race",
    28: "Helm Level Intros Game Over",
    29: "Factory Power Shed",
    30: "Galleon",
    31: "Galleon Krools Ship",
    32: "Batty Barrel Bandit Easy",
    33: "Japes Chunky Cave",
    34: "Dk Isles Overworld",
    35: "Krool Barrel Dk Target Game",
    36: "Factory Crusher Room",
    37: "Japes Barrel Blast",
    38: "Aztec",
    39: "Galleon Seal Race",
    40: "Nintendo Logo",
    41: "Aztec Barrel Blast",
    42: "Troff N Scoff",
    43: "Galleon Shipwreck Diddy Lanky Chunky",
    44: "Galleon Treasure Chest",
    45: "Galleon Mermaid",
    46: "Galleon Shipwreck Dk Tiny",
    47: "Galleon Shipwreck Lanky Tiny",
    48: "Fungi",
    49: "Galleon Lighthouse",
    50: "Krool Barrel Tiny Mushroom Game",
    51: "Galleon Mechanical Fish",
    52: "Fungi Ant Hill",
    53: "Battle Arena Beaver Brawl",
    54: "Galleon Barrel Blast",
    55: "Fungi Minecart",
    56: "Fungi Diddy Barn",
    57: "Fungi Diddy Attic",
    58: "Fungi Lanky Attic",
    59: "Fungi Dk Barn",
    60: "Fungi Spider",
    61: "Fungi Front Part Of Mill",
    62: "Fungi Rear Part Of Mill",
    63: "Fungi Mushroom Puzzle",
    64: "Fungi Giant Mushroom",
    65: "Stealthy Snoop Normal",
    66: "Mad Maze Maul Hard",
    67: "Stash Snatch Normal",
    68: "Mad Maze Maul Easy",
    69: "Mad Maze Maul Normal",
    70: "Fungi Mushroom Leap",
    71: "Fungi Shooting Game",
    72: "Caves",
    73: "Battle Arena Kritter Karnage",
    74: "Stash Snatch Easy",
    75: "Stash Snatch Hard",
    76: "Dk Rap",
    77: "Minecart Mayhem Easy",
    78: "Busy Barrel Barrage Easy",
    79: "Busy Barrel Barrage Normal",
    80: "Main Menu",
    81: "Title Screen Not For Resale Version",
    82: "Caves Beetle Race",
    83: "Fungi Dogadon",
    84: "Caves Igloo Tiny",
    85: "Caves Igloo Lanky",
    86: "Caves Igloo Dk",
    87: "Castle",
    88: "Castle Ballroom",
    89: "Caves Rotating Room",
    90: "Caves Shack Chunky",
    91: "Caves Shack Dk",
    92: "Caves Shack Diddy Middle Part",
    93: "Caves Shack Tiny",
    94: "Caves Lanky Hut",
    95: "Caves Igloo Chunky",
    96: "Splish Splash Salvage Normal",
    97: "Klumsy",
    98: "Caves Ice Castle",
    99: "Speedy Swing Sortie Easy",
    100: "Caves Igloo Diddy",
    101: "Krazy Kong Klamour Easy",
    102: "Big Bug Bash Very Easy",
    103: "Searchlight Seek Very Easy",
    104: "Beaver Bother Easy",
    105: "Castle Tower",
    106: "Castle Minecart",
    107: "Kong Battle Battle Arena",
    108: "Castle Crypt Lanky Tiny",
    109: "Kong Battle Arena 1",
    110: "Factory Barrel Blast",
    111: "Galleon Pufftoss",
    112: "Castle Crypt Dk Diddy Chunky",
    113: "Castle Museum",
    114: "Castle Library",
    115: "Kremling Kosh Easy",
    116: "Kremling Kosh Normal",
    117: "Kremling Kosh Hard",
    118: "Teetering Turtle Trouble Easy",
    119: "Teetering Turtle Trouble Normal",
    120: "Teetering Turtle Trouble Hard",
    121: "Batty Barrel Bandit Easy 2",
    122: "Batty Barrel Bandit Normal",
    123: "Batty Barrel Bandit Hard",
    124: "Mad Maze Maul Insane",
    125: "Stash Snatch Insane",
    126: "Stealthy Snoop Very Easy",
    127: "Stealthy Snoop Easy",
    128: "Stealthy Snoop Hard",
    129: "Minecart Mayhem Normal",
    130: "Minecart Mayhem Hard",
    131: "Busy Barrel Barrage Hard",
    132: "Splish Splash Salvage Hard",
    133: "Splish Splash Salvage Easy",
    134: "Speedy Swing Sortie Normal",
    135: "Speedy Swing Sortie Hard",
    136: "Beaver Bother Normal",
    137: "Beaver Bother Hard",
    138: "Searchlight Seek Easy",
    139: "Searchlight Seek Normal",
    140: "Searchlight Seek Hard",
    141: "Krazy Kong Klamour Normal",
    142: "Krazy Kong Klamour Hard",
    143: "Krazy Kong Klamour Insane",
    144: "Peril Path Panic Very Easy",
    145: "Peril Path Panic Easy",
    146: "Peril Path Panic Normal",
    147: "Peril Path Panic Hard",
    148: "Big Bug Bash Easy",
    149: "Big Bug Bash Normal",
    150: "Big Bug Bash Hard",
    151: "Castle Dungeon",
    152: "Helm Intro Story",
    153: "Dk Isles Dk Theatre",
    154: "Factory Mad Jack",
    155: "Battle Arena Arena Ambush",
    156: "Battle Arena More Kritter Karnage",
    157: "Battle Arena Forest Fracas",
    158: "Battle Arena Bish Bash Brawl",
    159: "Battle Arena Kamikaze Kremlings",
    160: "Battle Arena Plinth Panic",
    161: "Battle Arena Pinnacle Palaver",
    162: "Battle Arena Shockwave Showdown",
    163: "Castle Basement",
    164: "Castle Tree",
    165: "Krool Barrel Diddy Kremling Game",
    166: "Castle Chunky Toolshed",
    167: "Castle Trash Can",
    168: "Castle Greenhouse",
    169: "Japes Lobby",
    170: "Helm Lobby",
    171: "Dk House",
    172: "Rock Intro Story",
    173: "Aztec Lobby",
    174: "Galleon Lobby",
    175: "Factory Lobby",
    176: "Training Grounds",
    177: "Dive Barrel",
    178: "Fungi Lobby",
    179: "Galleon Submarine",
    180: "Orange Barrel",
    181: "Barrel Barrel",
    182: "Vine Barrel",
    183: "Castle Crypt",
    184: "Enguarde Arena",
    185: "Castle Car Race",
    186: "Caves Barrel Blast",
    187: "Castle Barrel Blast",
    188: "Fungi Barrel Blast",
    189: "Fairy Island",
    190: "Kong Battle Arena 2",
    191: "Rambi Arena",
    192: "Kong Battle Arena 3",
    193: "Castle Lobby",
    194: "Caves Lobby",
    195: "Dk Isles Snides Room",
    196: "Caves Army Dillo",
    197: "Aztec Dogadon",
    198: "Training Grounds End Sequence",
    199: "Castle King Kut Out",
    200: "Caves Shack Diddy Upper Part",
    201: "Krool Barrel Diddy Rocketbarrel Game",
    202: "Krool Barrel Lanky Shooting Game",
    203: "Krool Fight Dk Phase",
    204: "Krool Fight Diddy Phase",
    205: "Krool Fight Lanky Phase",
    206: "Krool Fight Tiny Phase",
    207: "Krool Fight Chunky Phase",
    208: "Bloopers Ending",
    209: "Krool Barrel Chunky Hidden Kremling Game",
    210: "Krool Barrel Tiny Pony Tail Twirl Game",
    211: "Krool Barrel Chunky Shooting Game",
    212: "Krool Barrel Dk Rambi Game",
    213: "Klumsy Ending",
    214: "Krools Shoe",
}
